### ISSUE TITLE
Permission Issues

### ISSUE THREAD

**Issue by gh-andrem** [hcoberdalhoff/MEMPSToolkit#1]
Thanks for this great tool to visualize conditional access policies.

While trying to use it, I noticed that I need to give the app registration more read permissions than just `Policy.Read.All` as I received an error `403 Forbidden` while running the `Write-ConditionalAccessPolicyToMermaid -pol $CAPols[0] -asHTML $true -asMarkdown $false -authToken $token` command.

Error message:
```Invoke-GraphRestRequest : The remote server returned an error: (403) Forbidden.
At C:\Program Files\WindowsPowerShell\Modules\MEMPSToolkit\0.0.21\MEMPSToolkit.psm1:2178 char:16
+ ...      $app = Invoke-GraphRestRequest -authToken $authToken -resource " ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
+ FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Invoke-GraphRestRequest
 
Executing Graph Rest Call against https://graph.microsoft.com/v1.0//applications?$filter=appId eq 
'000000000-1111-2222-3333-44444444444444' failed. See Error Log.
```

Another issue I've noticed was that group names would not resolve and just the group ID would be displayed in the HTML.

```
**Write-ConditionalAccessPolicyToMermaid -pol $CAPols[0] -asHTML $true -asMarkdown $false -authToken $token**
[SNIP]
includeGroups --> g_999999999-1111-2222-3333-44444444444444["999999999-1111-2222-3333-44444444444444"]
[SNAP]
```

The same would happen for users where the user name would not be resolved and just the user ID would be output.
```
**Write-ConditionalAccessPolicyToMermaid -pol $CAPols[0] -asHTML $true -asMarkdown $false -authToken $token**
[SNIP]
excludeUsers -->  u_123123123-1111-2222-3333-44444444444444["123123123-1111-2222-3333-44444444444444"]
[SNAP]
```

To sum it all up, I had to give the app registration the following permissions for it to run without issues:
- Application.Read.All [for apps to be queried]
- GroupMember.Read.All [for group names to be resolved]
- Policy.Read.All
- User.Read [default/delegated permission]
- User.Read.All [for user names to be resolved]

**Comment by hcoberdalhoff** [comment]
Hi, you are absolutely right :)

Btw, I also made sure that it does not error out, but will just not resolve the ids if permissions are missing. Check ab0ea5707c3369aaa517f96688cb86d43de796a4
