### ISSUE TITLE
Conditional Access Policy Export Improvement

### ISSUE THREAD

**Issue by gh-andrem** [hcoberdalhoff/MEMPSToolkit#2]
I wasn't sure if this should be added to the README or if you want to add this to your blog post on how to [Visualize Conditional Access Policies using PowerShell](https://notdoneyet.blog/powershell/aad/security/2021/06/29/Visualize-Cond-Acc-Pols.html) so I am posting it here as it might be useful for other users.

While visualizing quite a few conditional access policies from a tenant I thought it would be faster to add a loop around the last command that outputs the results to an HTML file that has the name of the Conditional Access Policy included.

```
Foreach ($i in $CAPols)
{
    Write-ConditionalAccessPolicyToMermaid -pol $i -asHTML $true -authToken $token | Out-File "C:\FOLDER\TO\ALL\CONDITIONAL ACCESS POLICIES\$($i.displayName)-CA-Policy.html"
}
```

**Comment by hcoberdalhoff** [comment]
Hi, have a look at 
https://github.com/hcoberdalhoff/MEMPSToolkit/blob/master/tools/ConditionalAccessVisualizer.ps1

This also solves some filename pains :)

I will update my blog and include it there. Thank you!
